# Módulo 5 Tarefa 1
## Base de nascidos vivos do DataSUS
O DataSUS disponibiliza diversos arquivos de dados com relação a seus segurados, conforme a [lei da transparência de informações públicas](https://www.sisgov.com/transparencia-acesso-informacao/#:~:text=A%20Lei%20da%20Transpar%C3%AAncia%20(LC,em%20um%20site%20na%20internet.). 

Essas informações podem ser obtidas pela internet [aqui](http://www2.datasus.gov.br/DATASUS/index.php?area=0901&item=1). Como o processo de obtenção desses arquivos foge um pouco do nosso escopo, deixamos o arquivo SINASC_RO_2019.csv` já como vai ser encontrado no DataSUS. O dicionário de dados está no arquivo `estrutura_sinasc_para_CD.pdf` (o nome do arquivo tal qual no portal do DataSUS).

### Nosso objetivo
Queremos deixar uma base organizada para podermos estudar a relação entre partos com risco para o bebê e algumas condições como tempo de parto, consultas de pré-natal etc.

#### Preparação da base
1. Carregue a base 'SINASC_RO_2019.csv'. Conte o número de registros e o número de registros não duplicados da base. Dica: você aprendeu um método que remove duplicados, encadeie este método com um outro método que conta o número de linhas. **Há linhas duplicadas?**  

2. Conte o número de valores *missing* por variável.  

3. Ok, no item anterior você deve ter achado pouco prático ler a informação de tantas variáveis, muitas delas nem devem ser interesantes. Então crie uma seleção dessa base somente com as colunas que interessam. São elas:
` 
['LOCNASC', 'IDADEMAE', 'ESTCIVMAE', 'ESCMAE', 'QTDFILVIVO', 
    'GESTACAO', 'GRAVIDEZ', 'CONSULTAS', 'APGAR5'] 
`
Refaça a contagem de valores *missings*.  

4. Apgar é uma *nota* que o pediatra dá ao bebê quando nasce de acordo com algumas características associadas principalmente à respiração. Apgar 1 e Apgar 5 são as notas 1 e 5 minutos do nascimento. Apgar5 será a nossa variável de interesse principal. Então remova todos os registros com Apgar5 não preenchido. Para esta seleção, conte novamente o número de linhas e o número de *missings*.  

5. observe que as variáveis `['ESTCIVMAE', 'CONSULTAS']` possuem o código `9`, que significa *ignorado*. Vamos assumir que o não preenchido é o mesmo que o código `9`.<br>
6. Substitua os valores faltantes da quantitativa (`QTDFILVIVO`) por zero.  
7. Das restantes, decida que valore te parece mais adequado (um 'não preenchido' ou um valor 'mais provável' como no item anterior) e preencha. Justifique. Lembre-se de que tratamento de dados é trabalho do cientista, e que estamos tomando decisões a todo o momento - não há necessariamente certo e errado aqui.  
8. O Apgar possui uma classificação indicando se o bebê passou por asfixia:
- Entre 8 e 10 está em uma faixa 'normal'. 
- Entre 6 e 7, significa que o recém-nascido passou por 'asfixia leve'. 
- Entre 4 e 5 significa 'asfixia moderada'.
- Entre 0 e 3 significa 'asfixia severa'.  

Crie uma categorização dessa variável com essa codificação e calcule as frequências dessa categorização.  
<br>
9. Renomeie as variáveis para que fiquem no *snake case*, ou seja, em letras minúsculas, com um *underscore* entre as palávras. Dica: repare que se você não quiser criar um *dataframe* novo, você vai precisar usar a opção `inplace = True`.

In [22]:
import pandas as pd
import requests
import numpy as np

# 1) seu código aqui
sinasc = pd.read_csv('SINASC_RO_2019.csv')
print(sinasc.shape)
sinasc.drop_duplicates().shape
# Não há duplicados

(27028, 69)

(27028, 69)

In [23]:
sinasc.head(10)

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
5,1,2516500.0,110001,1,33,5.0,1 a 3 anos,621005.0,2.0,1.0,...,5,6,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
6,1,2516500.0,110001,1,37,1.0,8 a 11 anos,999992.0,1.0,0.0,...,5,7,ATIVO,MUNIC,Novo Horizonte do Oeste,Rondônia,-11.70974,-61.99439,230.0,843.446
7,1,2516500.0,110001,1,27,2.0,12 anos ou mais,514120.0,0.0,0.0,...,5,8,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
8,1,2679477.0,110001,1,20,5.0,8 a 11 anos,621005.0,0.0,1.0,...,2,9,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
9,1,2679477.0,110001,1,30,2.0,1 a 3 anos,999992.0,1.0,1.0,...,5,10,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

In [24]:
sinasc.isna()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27023,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27024,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27025,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27026,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27027,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [25]:
# 2) seu código aqui
sinasc.isna().sum()

ORIGEM          0
CODESTAB      115
CODMUNNASC      0
LOCNASC         0
IDADEMAE        0
             ...
munResUf        0
munResLat       1
munResLon       1
munResAlt       1
munResArea      1
Length: 69, dtype: int64

In [26]:
# 3) seu código aqui
colunas_interesse = ['LOCNASC', 'IDADEMAE', 'ESTCIVMAE', 'ESCMAE', 
                     'QTDFILVIVO', 'GESTACAO', 'GRAVIDEZ', 'CONSULTAS', 'APGAR5']

# Selecionando somente essas colunas
df_selecionado = sinasc[colunas_interesse]

# Contando os valores ausentes por coluna
missing_por_coluna = df_selecionado.isnull().sum()

# Exibindo o resultado
print(missing_por_coluna)

LOCNASC          0
IDADEMAE         0
ESTCIVMAE      317
ESCMAE         312
QTDFILVIVO    1573
GESTACAO      1232
GRAVIDEZ        79
CONSULTAS        0
APGAR5         103
dtype: int64

In [27]:
# 4) seu código aqui
# Lista com as colunas de interesse
colunas_interesse = ['LOCNASC', 'IDADEMAE', 'ESTCIVMAE', 'ESCMAE', 
                     'QTDFILVIVO', 'GESTACAO', 'GRAVIDEZ', 'CONSULTAS', 'APGAR5']

# Selecionar apenas essas colunas
df_selecionado = sinasc[colunas_interesse]

# Remover linhas onde a coluna APGAR5 está ausente (missing)
df_apgar = df_selecionado.dropna(subset=['APGAR5'])

# Contar o número de linhas restantes após a remoção
num_linhas = len(df_apgar)

# Contar os valores ausentes nas colunas (depois da remoção de APGAR5 missing)
missing_restantes = df_apgar.isnull().sum()

# Exibir os resultados
print("Número de linhas restantes após remover APGAR5 ausente:", num_linhas)
print("\nValores missing por coluna:")
print(missing_restantes)

Número de linhas restantes após remover APGAR5 ausente: 26925

Valores missing por coluna:
LOCNASC          0
IDADEMAE         0
ESTCIVMAE      315
ESCMAE         310
QTDFILVIVO    1566
GESTACAO      1216
GRAVIDEZ        76
CONSULTAS        0
APGAR5           0
dtype: int64

In [28]:
# 5) seu código aqui
# Substituir o valor 9 por NaN nas colunas especificadas
colunas_para_substituir = ['ESTCIVMAE', 'CONSULTAS']
df_apgar[colunas_para_substituir] = df_apgar[colunas_para_substituir].replace(9, np.nan)

# Contar os valores ausentes (missing) após a substituição
missing_atualizado = df_apgar.isnull().sum()

# Exibir o resultado de forma clara
print("Valores ausentes atualizados (após substituir 9 por NaN):")
print(missing_atualizado)

Valores ausentes atualizados (após substituir 9 por NaN):
LOCNASC          0
IDADEMAE         0
ESTCIVMAE      459
ESCMAE         310
QTDFILVIVO    1566
GESTACAO      1216
GRAVIDEZ        76
CONSULTAS       50
APGAR5           0
dtype: int64

C:\Users\allte\AppData\Local\Temp\ipykernel_5940\3954153215.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_apgar[colunas_para_substituir] = df_apgar[colunas_para_substituir].replace(9, np.nan)

In [29]:
# 6) Seu código aqui
sinasc['QTDFILVIVO'].isna()

0        False
1        False
2        False
3        False
4        False
         ...
27023    False
27024    False
27025    False
27026    False
27027    False
Name: QTDFILVIVO, Length: 27028, dtype: bool

In [30]:
sinasc['QTDFILVIVO'].fillna(0)

0        0.0
1        1.0
2        2.0
3        0.0
4        1.0
        ...
27023    1.0
27024    0.0
27025    0.0
27026    1.0
27027    1.0
Name: QTDFILVIVO, Length: 27028, dtype: float64

In [31]:
# 7) seu código aqui
# Selecionar colunas de interesse
colunas = ['LOCNASC', 'IDADEMAE', 'ESTCIVMAE', 'ESCMAE',
           'QTDFILVIVO', 'GESTACAO', 'GRAVIDEZ', 'CONSULTAS', 'APGAR5']
df = sinasc[colunas].copy()

# Substituir códigos 'ignorados' por NaN
df.replace({'ESTCIVMAE': {9: np.nan}, 'CONSULTAS': {9: np.nan}}, inplace=True)

# Remover registros com APGAR5 ausente
df = df[df['APGAR5'].notna()]

# Estratégias de preenchimento definidas
preenchimentos = {
    'LOCNASC': 'ignorado',
    'IDADEMAE': df['IDADEMAE'].median(),
    'ESCMAE': df['ESCMAE'].mode()[0],
    'QTDFILVIVO': 0,
    'GESTACAO': df['GESTACAO'].mode()[0],
    'GRAVIDEZ': df['GRAVIDEZ'].mode()[0],
    'ESTCIVMAE': df['ESTCIVMAE'].mode()[0],
    'CONSULTAS': df['CONSULTAS'].mode()[0]
}

# Aplicar os preenchimentos
df.fillna(value=preenchimentos, inplace=True)

# Verificar se ainda há valores ausentes
print("Valores ausentes por coluna:")
print(df.isna().sum())

Valores ausentes por coluna:
LOCNASC       0
IDADEMAE      0
ESTCIVMAE     0
ESCMAE        0
QTDFILVIVO    0
GESTACAO      0
GRAVIDEZ      0
CONSULTAS     0
APGAR5        0
dtype: int64

In [32]:
sinasc.isna()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27023,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27024,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27025,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27026,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27027,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [33]:
# 8) seu código aqui
# Exemplo de DataFrame com a coluna Apgar
df_apgar = pd.DataFrame({
    'apgar': [9, 7, 5, 3, 10, 6, 4, 2, 8, 7, 5, 0, 9, 6]
})

# Categorização da variável Apgar
df_apgar.loc[(df_apgar['apgar'] >= 8) & (df_apgar['apgar'] <= 10), 'apgar_cat'] = 'normal'
df_apgar.loc[(df_apgar['apgar'] >= 6) & (df_apgar['apgar'] <= 7), 'apgar_cat'] = 'asfixia_leve'
df_apgar.loc[(df_apgar['apgar'] >= 4) & (df_apgar['apgar'] <= 5), 'apgar_cat'] = 'asfixia_moderada'
df_apgar.loc[(df_apgar['apgar'] >= 0) & (df_apgar['apgar'] <= 3), 'apgar_cat'] = 'asfixia_severa'

df_apgar

    apgar         apgar_cat
0       9            normal
1       7      asfixia_leve
2       5  asfixia_moderada
3       3    asfixia_severa
4      10            normal
5       6      asfixia_leve
6       4  asfixia_moderada
7       2    asfixia_severa
8       8            normal
9       7      asfixia_leve
10      5  asfixia_moderada
11      0    asfixia_severa
12      9            normal
13      6      asfixia_leve

In [34]:
# Frequência das categorias
frequencias = df_apgar['apgar_cat'].value_counts()

frequencias

apgar_cat
normal              4
asfixia_leve        4
asfixia_moderada    3
asfixia_severa      3
Name: count, dtype: int64

In [35]:
# 9) seu código aqui
import pandas as pd

# Criando um DataFrame com nomes de colunas mistos (com espaços)
df_apgar = pd.DataFrame({
    'Apgar': [9, 7, 5, 3],
    'Apgar Cat': ['normal', 'asfixia_leve', 'asfixia_moderada', 'asfixia_severa']
})


def para_snake_case_simples(coluna):
    coluna = coluna.replace(" ", "_")  
    coluna = coluna.lower()           
    return coluna

df_apgar.rename(columns=lambda x: para_snake_case_simples(x), inplace=True)

df_apgar

   apgar         apgar_cat
0      9            normal
1      7      asfixia_leve
2      5  asfixia_moderada
3      3    asfixia_severa